using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace AGUI.Abstractions;

/// <summary>
/// Source-generated JSON serializer context for AG-UI types.
/// Types are added incrementally as each slice is implemented.
/// </summary>
[JsonSerializable(typeof(BaseEvent))]
[JsonSerializable(typeof(RunStartedEvent))]
[JsonSerializable(typeof(RunFinishedEvent))]
[JsonSerializable(typeof(RunErrorEvent))]
[JsonSerializable(typeof(StepStartedEvent))]
[JsonSerializable(typeof(StepFinishedEvent))]
[JsonSerializable(typeof(AGUIInterrupt))]
[JsonSerializable(typeof(IList<AGUIInterrupt>))]
[JsonSerializable(typeof(AGUIResume))]
[JsonSerializable(typeof(IList<AGUIResume>))]
[JsonSerializable(typeof(AGUIContext))]
[JsonSerializable(typeof(IList<AGUIContext>))]
[JsonSerializable(typeof(RunFinishedOutcome))]
[JsonSerializable(typeof(RunFinishedSuccessOutcome))]
[JsonSerializable(typeof(RunFinishedInterruptOutcome))]
[JsonSerializable(typeof(AGUIToolApprovalPayload))]
[JsonSerializable(typeof(AGUIToolApprovalResumePayload))]
[JsonSerializable(typeof(AGUIToolCallInfo))]
[JsonSerializable(typeof(RunAgentInput))]
[JsonSerializable(typeof(TextMessageStartEvent))]
[JsonSerializable(typeof(TextMessageContentEvent))]
[JsonSerializable(typeof(TextMessageEndEvent))]
[JsonSerializable(typeof(AGUIMessage))]
[JsonSerializable(typeof(AGUIUserMessage))]
[JsonSerializable(typeof(AGUIAssistantMessage))]
[JsonSerializable(typeof(AGUISystemMessage))]
[JsonSerializable(typeof(AGUIDeveloperMessage))]
[JsonSerializable(typeof(AGUIToolMessage))]
[JsonSerializable(typeof(AGUIActivityMessage))]
[JsonSerializable(typeof(AGUIReasoningMessage))]
[JsonSerializable(typeof(AGUIToolCall))]
[JsonSerializable(typeof(AGUIToolCallFunction))]
[JsonSerializable(typeof(AGUIInputContent))]
[JsonSerializable(typeof(AGUITextInputContent))]
[JsonSerializable(typeof(AGUIImageInputContent))]
[JsonSerializable(typeof(AGUIAudioInputContent))]
[JsonSerializable(typeof(AGUIVideoInputContent))]
[JsonSerializable(typeof(AGUIDocumentInputContent))]
[JsonSerializable(typeof(AGUIBinaryInputContent))]
[JsonSerializable(typeof(AGUIInputContentSource))]
[JsonSerializable(typeof(AGUIInputContentDataSource))]
[JsonSerializable(typeof(AGUIInputContentUrlSource))]
[JsonSerializable(typeof(ToolCallStartEvent))]
[JsonSerializable(typeof(ToolCallArgsEvent))]
[JsonSerializable(typeof(ToolCallEndEvent))]
[JsonSerializable(typeof(ToolCallResultEvent))]
[JsonSerializable(typeof(AGUITool))]
[JsonSerializable(typeof(StateSnapshotEvent))]
[JsonSerializable(typeof(StateDeltaEvent))]
[JsonSerializable(typeof(ReasoningStartEvent))]
[JsonSerializable(typeof(ReasoningMessageStartEvent))]
[JsonSerializable(typeof(ReasoningMessageContentEvent))]
[JsonSerializable(typeof(ReasoningMessageEndEvent))]
[JsonSerializable(typeof(ReasoningMessageChunkEvent))]
[JsonSerializable(typeof(ReasoningEndEvent))]
[JsonSerializable(typeof(ReasoningEncryptedValueEvent))]
[JsonSerializable(typeof(ActivitySnapshotEvent))]
[JsonSerializable(typeof(ActivityDeltaEvent))]
[JsonSerializable(typeof(CustomEvent))]
[JsonSerializable(typeof(RawEvent))]
[JsonSerializable(typeof(MessagesSnapshotEvent))]
[JsonSerializable(typeof(AgentCapabilities))]
[JsonSerializable(typeof(IdentityCapabilities))]
[JsonSerializable(typeof(TransportCapabilities))]
[JsonSerializable(typeof(ToolsCapabilities))]
[JsonSerializable(typeof(OutputCapabilities))]
[JsonSerializable(typeof(StateCapabilities))]
[JsonSerializable(typeof(MultiAgentCapabilities))]
[JsonSerializable(typeof(SubAgentInfo))]
[JsonSerializable(typeof(ReasoningCapabilities))]
[JsonSerializable(typeof(MultimodalCapabilities))]
[JsonSerializable(typeof(MultimodalInputCapabilities))]
[JsonSerializable(typeof(MultimodalOutputCapabilities))]
[JsonSerializable(typeof(ExecutionCapabilities))]
[JsonSerializable(typeof(HumanInTheLoopCapabilities))]
[JsonSerializable(typeof(IDictionary<string, object?>))]
[JsonSerializable(typeof(JsonElement))]
[JsonSerializable(typeof(JsonElement?))]
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
public partial class AGUIJsonSerializerContext : JsonSerializerContext
{
}
